export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";

// export const DELETE_POSTS = 'DELETE_POSTS';
// export const DELETE_POSTS_SUCCESS = 'DELETE_POSTS_SUCCESS';
// export const DELETE_POSTS_FAILURE = 'DELETE_POSTS_FAILURE';

// export const EDIT_POSTS = 'EDIT_POSTS';
// export const EDIT_POSTS_SUCCESS = 'EDIT_POSTS_SUCCESS';
// export const EDIT_POSTS_FAILURE = 'EDIT_POSTS_FAILURE';
